<?php

use Illuminate\Database\Seeder;
use App\Lga;
class LGAtableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $lgas = [
            [ "state" => "abia", "state_id" => 1, "lg_name" => "Aba North" ],
            [ "state" => "abia", "state_id" => 1, "lg_name" => "Aba South" ],
            [ "state" => "abia", "state_id" => 1, "lg_name" => "Arochukwu" ],
            [ "state" => "abia", "state_id" => 1, "lg_name" => "Bende" ],
            [ "state" => "abia", "state_id" => 1, "lg_name" => "Ikwuano" ],
            [ "state" => "abia", "state_id" => 1, "lg_name" => "Isiala Ngwa North" ],
            [ "state" => "abia", "state_id" => 1, "lg_name" => "Isiala Ngwa South" ],
            [ "state" => "abia", "state_id" => 1, "lg_name" => "Isuikwuato" ],
            [ "state" => "abia", "state_id" => 1, "lg_name" => "Obi Ngwa" ],
            [ "state" => "abia", "state_id" => 1, "lg_name" => "Ohafia" ],
            [ "state" => "abia", "state_id" => 1, "lg_name" => "Osisioma" ],
            [ "state" => "abia", "state_id" => 1, "lg_name" => "Ugwunagbo" ],
            [ "state" => "abia", "state_id" => 1, "lg_name" => "Ukwa East" ],
            [ "state" => "abia", "state_id" => 1, "lg_name" => "Ukwa West" ],
            [ "state" => "abia", "state_id" => 1, "lg_name" => "Umuahia North" ],
            [ "state" => "abia", "state_id" => 1, "lg_name" => "Umuahia South" ],
            [ "state" => "abia", "state_id" => 1, "lg_name" => "Umu Nneochi" ],
            [ "state" => "adamawa", "state_id" => 2, "lg_name" => "Demsa" ],
            [ "state" => "adamawa", "state_id" => 2, "lg_name" => "Fufure" ],
            [ "state" => "adamawa", "state_id" => 2, "lg_name" => "Ganye" ],
            [ "state" => "adamawa", "state_id" => 2, "lg_name" => "Gayuk" ],
            [ "state" => "adamawa", "state_id" => 2, "lg_name" => "Gombi" ],
            [ "state" => "adamawa", "state_id" => 2, "lg_name" => "Grie" ],
            [ "state" => "adamawa", "state_id" => 2, "lg_name" => "Hong" ],
            [ "state" => "adamawa", "state_id" => 2, "lg_name" => "Jada" ],
            [ "state" => "adamawa", "state_id" => 2, "lg_name" => "Lamurde" ],
            [ "state" => "adamawa", "state_id" => 2, "lg_name" => "Madagali" ],
            [ "state" => "adamawa", "state_id" => 2, "lg_name" => "Maiha" ],
            [ "state" => "adamawa", "state_id" => 2, "lg_name" => "Mayo Belwa" ],
            [ "state" => "adamawa", "state_id" => 2, "lg_name" => "Michika" ],
            [ "state" => "adamawa", "state_id" => 2, "lg_name" => "Mubi North" ],
            [ "state" => "adamawa", "state_id" => 2, "lg_name" => "Mubi South" ],
            [ "state" => "adamawa", "state_id" => 2, "lg_name" => "Numan" ],
            [ "state" => "adamawa", "state_id" => 2, "lg_name" => "Shelleng" ],
            [ "state" => "adamawa", "state_id" => 2, "lg_name" => "Song" ],
            [ "state" => "adamawa", "state_id" => 2, "lg_name" => "Toungo" ],
            [ "state" => "adamawa", "state_id" => 2, "lg_name" => "Yola North" ],
            [ "state" => "adamawa", "state_id" => 2, "lg_name" => "Yola South" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Abak" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Eastern Obolo" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Eket" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Esit Eket" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Essien Udim" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Etim Ekpo" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Etinan" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Ibeno" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Ibesikpo Asutan" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Ibiono-Ibom" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Ika" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Ikono" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Ikot Abasi" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Ikot Ekpene" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Ini" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Itu" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Mbo" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Mkpat-Enin" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Nsit-Atai" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Nsit-Ibom" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Nsit-Ubium" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Obot Akara" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Okobo" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Onna" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Oron" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Oruk Anam" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Udung-Uko" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Ukanafun" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Uruan" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Urue-Offong Oruko" ],
            [ "state" => "akwa-ibom", "state_id" => 3, "lg_name" => "Uyo" ],
            [ "state" => "anambra", "state_id" => 4, "lg_name" => "Aguata" ],
            [ "state" => "anambra", "state_id" => 4, "lg_name" => "Anambra East" ],
            [ "state" => "anambra", "state_id" => 4, "lg_name" => "Anambra West" ],
            [ "state" => "anambra", "state_id" => 4, "lg_name" => "Anaocha" ],
            [ "state" => "anambra", "state_id" => 4, "lg_name" => "Awka North" ],
            [ "state" => "anambra", "state_id" => 4, "lg_name" => "Awka South" ],
            [ "state" => "anambra", "state_id" => 4, "lg_name" => "Ayamelum" ],
            [ "state" => "anambra", "state_id" => 4, "lg_name" => "Dunukofia" ],
            [ "state" => "anambra", "state_id" => 4, "lg_name" => "Ekwusigo" ],
            [ "state" => "anambra", "state_id" => 4, "lg_name" => "Idemili North" ],
            [ "state" => "anambra", "state_id" => 4, "lg_name" => "Idemili South" ],
            [ "state" => "anambra", "state_id" => 4, "lg_name" => "Ihiala" ],
            [ "state" => "anambra", "state_id" => 4, "lg_name" => "Njikoka" ],
            [ "state" => "anambra", "state_id" => 4, "lg_name" => "Nnewi North" ],
            [ "state" => "anambra", "state_id" => 4, "lg_name" => "Nnewi South" ],
            [ "state" => "anambra", "state_id" => 4, "lg_name" => "Ogbaru" ],
            [ "state" => "anambra", "state_id" => 4, "lg_name" => "Onitsha North" ],
            [ "state" => "anambra", "state_id" => 4, "lg_name" => "Onitsha South" ],
            [ "state" => "anambra", "state_id" => 4, "lg_name" => "Orumba North" ],
            [ "state" => "anambra", "state_id" => 4, "lg_name" => "Orumba South" ],
            [ "state" => "anambra", "state_id" => 4, "lg_name" => "Oyi" ],
            [ "state" => "bauchi", "state_id" => 5, "lg_name" => "Alkaleri" ],
            [ "state" => "bauchi", "state_id" => 5, "lg_name" => "Bauchi" ],
            [ "state" => "bauchi", "state_id" => 5, "lg_name" => "Bogoro" ],
            [ "state" => "bauchi", "state_id" => 5, "lg_name" => "Damban" ],
            [ "state" => "bauchi", "state_id" => 5, "lg_name" => "Darazo" ],
            [ "state" => "bauchi", "state_id" => 5, "lg_name" => "Dass" ],
            [ "state" => "bauchi", "state_id" => 5, "lg_name" => "Gamawa" ],
            [ "state" => "bauchi", "state_id" => 5, "lg_name" => "Ganjuwa" ],
            [ "state" => "bauchi", "state_id" => 5, "lg_name" => "Giade" ],
            [ "state" => "bauchi", "state_id" => 5, "lg_name" => "Itas Gadau" ],
            [ "state" => "bauchi", "state_id" => 5, "lg_name" => "Jama'are" ],
            [ "state" => "bauchi", "state_id" => 5, "lg_name" => "Katagum" ],
            [ "state" => "bauchi", "state_id" => 5, "lg_name" => "Kirfi" ],
            [ "state" => "bauchi", "state_id" => 5, "lg_name" => "Misau" ],
            [ "state" => "bauchi", "state_id" => 5, "lg_name" => "Ningi" ],
            [ "state" => "bauchi", "state_id" => 5, "lg_name" => "Shira" ],
            [ "state" => "bauchi", "state_id" => 5, "lg_name" => "Tafawa Balewa" ],
            [ "state" => "bauchi", "state_id" => 5, "lg_name" => "Toro" ],
            [ "state" => "bauchi", "state_id" => 5, "lg_name" => "Warji" ],
            [ "state" => "bauchi", "state_id" => 5, "lg_name" => "Zaki" ],
            [ "state" => "bayelsa", "state_id" => 6, "lg_name" => "Brass" ],
            [ "state" => "bayelsa", "state_id" => 6, "lg_name" => "Ekeremor" ],
            [ "state" => "bayelsa", "state_id" => 6, "lg_name" => "Kolokuma Opokuma" ],
            [ "state" => "bayelsa", "state_id" => 6, "lg_name" => "Nembe" ],
            [ "state" => "bayelsa", "state_id" => 6, "lg_name" => "Ogbia" ],
            [ "state" => "bayelsa", "state_id" => 6, "lg_name" => "Sagbama" ],
            [ "state" => "bayelsa", "state_id" => 6, "lg_name" => "Southern Ijaw" ],
            [ "state" => "bayelsa", "state_id" => 6, "lg_name" => "Yenagoa" ],
            [ "state" => "benue", "state_id" => 7, "lg_name" => "Agatu" ],
            [ "state" => "benue", "state_id" => 7, "lg_name" => "Apa" ],
            [ "state" => "benue", "state_id" => 7, "lg_name" => "Ado" ],
            [ "state" => "benue", "state_id" => 7, "lg_name" => "Buruku" ],
            [ "state" => "benue", "state_id" => 7, "lg_name" => "Gboko" ],
            [ "state" => "benue", "state_id" => 7, "lg_name" => "Guma" ],
            [ "state" => "benue", "state_id" => 7, "lg_name" => "Gwer East" ],
            [ "state" => "benue", "state_id" => 7, "lg_name" => "Gwer West" ],
            [ "state" => "benue", "state_id" => 7, "lg_name" => "Katsina-Ala" ],
            [ "state" => "benue", "state_id" => 7, "lg_name" => "Konshisha" ],
            [ "state" => "benue", "state_id" => 7, "lg_name" => "Kwande" ],
            [ "state" => "benue", "state_id" => 7, "lg_name" => "Logo" ],
            [ "state" => "benue", "state_id" => 7, "lg_name" => "Makurdi" ],
            [ "state" => "benue", "state_id" => 7, "lg_name" => "Obi" ],
            [ "state" => "benue", "state_id" => 7, "lg_name" => "Ogbadibo" ],
            [ "state" => "benue", "state_id" => 7, "lg_name" => "Ohimini" ],
            [ "state" => "benue", "state_id" => 7, "lg_name" => "Oju" ],
            [ "state" => "benue", "state_id" => 7, "lg_name" => "Okpokwu" ],
            [ "state" => "benue", "state_id" => 7, "lg_name" => "Oturkpo" ],
            [ "state" => "benue", "state_id" => 7, "lg_name" => "Tarka" ],
            [ "state" => "benue", "state_id" => 7, "lg_name" => "Ukum" ],
            [ "state" => "benue", "state_id" => 7, "lg_name" => "Ushongo" ],
            [ "state" => "benue", "state_id" => 7, "lg_name" => "Vandeikya" ],
            [ "state" => "borno", "state_id" => 8, "lg_name" => "Abadam" ],
            [ "state" => "borno", "state_id" => 8, "lg_name" => "Askira Uba" ],
            [ "state" => "borno", "state_id" => 8, "lg_name" => "Bama" ],
            [ "state" => "borno", "state_id" => 8, "lg_name" => "Bayo" ],
            [ "state" => "borno", "state_id" => 8, "lg_name" => "Biu" ],
            [ "state" => "borno", "state_id" => 8, "lg_name" => "Chibok" ],
            [ "state" => "borno", "state_id" => 8, "lg_name" => "Damboa" ],
            [ "state" => "borno", "state_id" => 8, "lg_name" => "Dikwa" ],
            [ "state" => "borno", "state_id" => 8, "lg_name" => "Gubio" ],
            [ "state" => "borno", "state_id" => 8, "lg_name" => "Guzamala" ],
            [ "state" => "borno", "state_id" => 8, "lg_name" => "Gwoza" ],
            [ "state" => "borno", "state_id" => 8, "lg_name" => "Hawul" ],
            [ "state" => "borno", "state_id" => 8, "lg_name" => "Jere" ],
            [ "state" => "borno", "state_id" => 8, "lg_name" => "Kaga" ],
            [ "state" => "borno", "state_id" => 8, "lg_name" => "Kala Balge" ],
            [ "state" => "borno", "state_id" => 8, "lg_name" => "Konduga" ],
            [ "state" => "borno", "state_id" => 8, "lg_name" => "Kukawa" ],
            [ "state" => "borno", "state_id" => 8, "lg_name" => "Kwaya Kusar" ],
            [ "state" => "borno", "state_id" => 8, "lg_name" => "Mafa" ],
            [ "state" => "borno", "state_id" => 8, "lg_name" => "Magumeri" ],
            [ "state" => "borno", "state_id" => 8, "lg_name" => "Maiduguri" ],
            [ "state" => "borno", "state_id" => 8, "lg_name" => "Marte" ],
            [ "state" => "borno", "state_id" => 8, "lg_name" => "Mobbar" ],
            [ "state" => "borno", "state_id" => 8, "lg_name" => "Monguno" ],
            [ "state" => "borno", "state_id" => 8, "lg_name" => "Ngala" ],
            [ "state" => "borno", "state_id" => 8, "lg_name" => "Nganzai" ],
            [ "state" => "borno", "state_id" => 8, "lg_name" => "Shani" ],
            [ "state" => "cross-river", "state_id" => 9, "lg_name" => "Abi" ],
            [ "state" => "cross-river", "state_id" => 9, "lg_name" => "Akamkpa" ],
            [ "state" => "cross-river", "state_id" => 9, "lg_name" => "Akpabuyo" ],
            [ "state" => "cross-river", "state_id" => 9, "lg_name" => "Bakassi" ],
            [ "state" => "cross-river", "state_id" => 9, "lg_name" => "Bekwarra" ],
            [ "state" => "cross-river", "state_id" => 9, "lg_name" => "Biase" ],
            [ "state" => "cross-river", "state_id" => 9, "lg_name" => "Boki" ],
            [ "state" => "cross-river", "state_id" => 9, "lg_name" => "Calabar Municipal" ],
            [ "state" => "cross-river", "state_id" => 9, "lg_name" => "Calabar South" ],
            [ "state" => "cross-river", "state_id" => 9, "lg_name" => "Etung" ],
            [ "state" => "cross-river", "state_id" => 9, "lg_name" => "Ikom" ],
            [ "state" => "cross-river", "state_id" => 9, "lg_name" => "Obanliku" ],
            [ "state" => "cross-river", "state_id" => 9, "lg_name" => "Obubra" ],
            [ "state" => "cross-river", "state_id" => 9, "lg_name" => "Obudu" ],
            [ "state" => "cross-river", "state_id" => 9, "lg_name" => "Odukpani" ],
            [ "state" => "cross-river", "state_id" => 9, "lg_name" => "Ogoja" ],
            [ "state" => "cross-river", "state_id" => 9, "lg_name" => "Yakuur" ],
            [ "state" => "cross-river", "state_id" => 9, "lg_name" => "Yala" ],
            [ "state" => "delta", "state_id" => 10, "lg_name" => "Aniocha North" ],
            [ "state" => "delta", "state_id" => 10, "lg_name" => "Aniocha South" ],
            [ "state" => "delta", "state_id" => 10, "lg_name" => "Bomadi" ],
            [ "state" => "delta", "state_id" => 10, "lg_name" => "Burutu" ],
            [ "state" => "delta", "state_id" => 10, "lg_name" => "Ethiope East" ],
            [ "state" => "delta", "state_id" => 10, "lg_name" => "Ethiope West" ],
            [ "state" => "delta", "state_id" => 10, "lg_name" => "Ika North East" ],
            [ "state" => "delta", "state_id" => 10, "lg_name" => "Ika South" ],
            [ "state" => "delta", "state_id" => 10, "lg_name" => "Isoko North" ],
            [ "state" => "delta", "state_id" => 10, "lg_name" => "Isoko South" ],
            [ "state" => "delta", "state_id" => 10, "lg_name" => "Ndokwa East" ],
            [ "state" => "delta", "state_id" => 10, "lg_name" => "Ndokwa West" ],
            [ "state" => "delta", "state_id" => 10, "lg_name" => "Okpe" ],
            [ "state" => "delta", "state_id" => 10, "lg_name" => "Oshimili North" ],
            [ "state" => "delta", "state_id" => 10, "lg_name" => "Oshimili South" ],
            [ "state" => "delta", "state_id" => 10, "lg_name" => "Patani" ],
            [ "state" => "delta", "state_id" => 10, "lg_name" => "Sapele" ],
            [ "state" => "delta", "state_id" => 10, "lg_name" => "Udu" ],
            [ "state" => "delta", "state_id" => 10, "lg_name" => "Ughelli North" ],
            [ "state" => "delta", "state_id" => 10, "lg_name" => "Ughelli South" ],
            [ "state" => "delta", "state_id" => 10, "lg_name" => "Ukwuani" ],
            [ "state" => "delta", "state_id" => 10, "lg_name" => "Uvwie" ],
            [ "state" => "delta", "state_id" => 10, "lg_name" => "Warri North" ],
            [ "state" => "delta", "state_id" => 10, "lg_name" => "Warri South" ],
            [ "state" => "delta", "state_id" => 10, "lg_name" => "Warri South West" ],
            [ "state" => "ebonyi", "state_id" => 11, "lg_name" => "Abakaliki" ],
            [ "state" => "ebonyi", "state_id" => 11, "lg_name" => "Afikpo North" ],
            [ "state" => "ebonyi", "state_id" => 11, "lg_name" => "Afikpo South Edda" ],
            [ "state" => "ebonyi", "state_id" => 11, "lg_name" => "Ebonyi" ],
            [ "state" => "ebonyi", "state_id" => 11, "lg_name" => "Ezza North" ],
            [ "state" => "ebonyi", "state_id" => 11, "lg_name" => "Ezza South" ],
            [ "state" => "ebonyi", "state_id" => 11, "lg_name" => "Ikwo" ],
            [ "state" => "ebonyi", "state_id" => 11, "lg_name" => "Ishielu" ],
            [ "state" => "ebonyi", "state_id" => 11, "lg_name" => "Ivo" ],
            [ "state" => "ebonyi", "state_id" => 11, "lg_name" => "Izzi" ],
            [ "state" => "ebonyi", "state_id" => 11, "lg_name" => "Ohaozara" ],
            [ "state" => "ebonyi", "state_id" => 11, "lg_name" => "Ohaukwu" ],
            [ "state" => "ebonyi", "state_id" => 11, "lg_name" => "Onicha" ],
            [ "state" => "edo", "state_id" => 12, "lg_name" => "Akoko-Edo" ],
            [ "state" => "edo", "state_id" => 12, "lg_name" => "Egor" ],
            [ "state" => "edo", "state_id" => 12, "lg_name" => "Esan Central" ],
            [ "state" => "edo", "state_id" => 12, "lg_name" => "Esan North-East" ],
            [ "state" => "edo", "state_id" => 12, "lg_name" => "Esan South-East" ],
            [ "state" => "edo", "state_id" => 12, "lg_name" => "Esan West" ],
            [ "state" => "edo", "state_id" => 12, "lg_name" => "Etsako Central" ],
            [ "state" => "edo", "state_id" => 12, "lg_name" => "Etsako East" ],
            [ "state" => "edo", "state_id" => 12, "lg_name" => "Etsako West" ],
            [ "state" => "edo", "state_id" => 12, "lg_name" => "Igueben" ],
            [ "state" => "edo", "state_id" => 12, "lg_name" => "Ikpoba Okha" ],
            [ "state" => "edo", "state_id" => 12, "lg_name" => "Orhionmwon" ],
            [ "state" => "edo", "state_id" => 12, "lg_name" => "Oredo" ],
            [ "state" => "edo", "state_id" => 12, "lg_name" => "Ovia North-East" ],
            [ "state" => "edo", "state_id" => 12, "lg_name" => "Ovia South-West" ],
            [ "state" => "edo", "state_id" => 12, "lg_name" => "Owan East" ],
            [ "state" => "edo", "state_id" => 12, "lg_name" => "Owan West" ],
            [ "state" => "edo", "state_id" => 12, "lg_name" => "Uhunmwonde" ],
            [ "state" => "ekiti", "state_id" => 13, "lg_name" => "Ado Ekiti" ],
            [ "state" => "ekiti", "state_id" => 13, "lg_name" => "Efon" ],
            [ "state" => "ekiti", "state_id" => 13, "lg_name" => "Ekiti East" ],
            [ "state" => "ekiti", "state_id" => 13, "lg_name" => "Ekiti South-West" ],
            [ "state" => "ekiti", "state_id" => 13, "lg_name" => "Ekiti West" ],
            [ "state" => "ekiti", "state_id" => 13, "lg_name" => "Emure" ],
            [ "state" => "ekiti", "state_id" => 13, "lg_name" => "Gbonyin" ],
            [ "state" => "ekiti", "state_id" => 13, "lg_name" => "Ido Osi" ],
            [ "state" => "ekiti", "state_id" => 13, "lg_name" => "Ijero" ],
            [ "state" => "ekiti", "state_id" => 13, "lg_name" => "Ikere" ],
            [ "state" => "ekiti", "state_id" => 13, "lg_name" => "Ikole" ],
            [ "state" => "ekiti", "state_id" => 13, "lg_name" => "Ilejemeje" ],
            [ "state" => "ekiti", "state_id" => 13, "lg_name" => "Irepodun Ifelodun" ],
            [ "state" => "ekiti", "state_id" => 13, "lg_name" => "Ise Orun" ],
            [ "state" => "ekiti", "state_id" => 13, "lg_name" => "Moba" ],
            [ "state" => "ekiti", "state_id" => 13, "lg_name" => "Oye" ],
            [ "state" => "enugu", "state_id" => 14, "lg_name" => "Udi" ],
            [ "state" => "enugu", "state_id" => 14, "lg_name" => "Aninri" ],
            [ "state" => "enugu", "state_id" => 14, "lg_name" => "Awgu" ],
            [ "state" => "enugu", "state_id" => 14, "lg_name" => "Enugu East" ],
            [ "state" => "enugu", "state_id" => 14, "lg_name" => "Enugu North" ],
            [ "state" => "enugu", "state_id" => 14, "lg_name" => "Enugu South" ],
            [ "state" => "enugu", "state_id" => 14, "lg_name" => "Ezeagu" ],
            [ "state" => "enugu", "state_id" => 14, "lg_name" => "Igbo Etiti" ],
            [ "state" => "enugu", "state_id" => 14, "lg_name" => "Igbo Eze North" ],
            [ "state" => "enugu", "state_id" => 14, "lg_name" => "Igbo Eze South" ],
            [ "state" => "enugu", "state_id" => 14, "lg_name" => "Isi Uzo" ],
            [ "state" => "enugu", "state_id" => 14, "lg_name" => "Nkanu East" ],
            [ "state" => "enugu", "state_id" => 14, "lg_name" => "Nkanu West" ],
            [ "state" => "enugu", "state_id" => 14, "lg_name" => "Nsukka" ],
            [ "state" => "enugu", "state_id" => 14, "lg_name" => "Oji River" ],
            [ "state" => "enugu", "state_id" => 14, "lg_name" => "Udenu" ],
            [ "state" => "enugu", "state_id" => 14, "lg_name" => "Uzo-Uwani" ],
            [ "state" => "fct", "state_id" => 15, "lg_name" => "Abaji" ],
            [ "state" => "fct", "state_id" => 15, "lg_name" => "Bwari" ],
            [ "state" => "fct", "state_id" => 15, "lg_name" => "Gwagwalada" ],
            [ "state" => "fct", "state_id" => 15, "lg_name" => "Kuje" ],
            [ "state" => "fct", "state_id" => 15, "lg_name" => "Kwali" ],
            [ "state" => "fct", "state_id" => 15, "lg_name" => "Municipal Area Council" ],
            [ "state" => "gombe", "state_id" => 16, "lg_name" => "Akko" ],
            [ "state" => "gombe", "state_id" => 16, "lg_name" => "Balanga" ],
            [ "state" => "gombe", "state_id" => 16, "lg_name" => "Billiri" ],
            [ "state" => "gombe", "state_id" => 16, "lg_name" => "Dukku" ],
            [ "state" => "gombe", "state_id" => 16, "lg_name" => "Funakaye" ],
            [ "state" => "gombe", "state_id" => 16, "lg_name" => "Gombe" ],
            [ "state" => "gombe", "state_id" => 16, "lg_name" => "Kaltungo" ],
            [ "state" => "gombe", "state_id" => 16, "lg_name" => "Kwami" ],
            [ "state" => "gombe", "state_id" => 16, "lg_name" => "Nafada" ],
            [ "state" => "gombe", "state_id" => 16, "lg_name" => "Shongom" ],
            [ "state" => "gombe", "state_id" => 16, "lg_name" => "Yamaltu Deba" ],
            [ "state" => "imo", "state_id" => 17, "lg_name" => "Aboh Mbaise" ],
            [ "state" => "imo", "state_id" => 17, "lg_name" => "Ahiazu Mbaise" ],
            [ "state" => "imo", "state_id" => 17, "lg_name" => "Ehime Mbano" ],
            [ "state" => "imo", "state_id" => 17, "lg_name" => "Ezinihitte" ],
            [ "state" => "imo", "state_id" => 17, "lg_name" => "Ideato North" ],
            [ "state" => "imo", "state_id" => 17, "lg_name" => "Ideato South" ],
            [ "state" => "imo", "state_id" => 17, "lg_name" => "Ihitte Uboma" ],
            [ "state" => "imo", "state_id" => 17, "lg_name" => "Ikeduru" ],
            [ "state" => "imo", "state_id" => 17, "lg_name" => "Isiala Mbano" ],
            [ "state" => "imo", "state_id" => 17, "lg_name" => "Isu" ],
            [ "state" => "imo", "state_id" => 17, "lg_name" => "Mbaitoli" ],
            [ "state" => "imo", "state_id" => 17, "lg_name" => "Ngor Okpala" ],
            [ "state" => "imo", "state_id" => 17, "lg_name" => "Njaba" ],
            [ "state" => "imo", "state_id" => 17, "lg_name" => "Nkwerre" ],
            [ "state" => "imo", "state_id" => 17, "lg_name" => "Nwangele" ],
            [ "state" => "imo", "state_id" => 17, "lg_name" => "Obowo" ],
            [ "state" => "imo", "state_id" => 17, "lg_name" => "Oguta" ],
            [ "state" => "imo", "state_id" => 17, "lg_name" => "Ohaji Egbema" ],
            [ "state" => "imo", "state_id" => 17, "lg_name" => "Okigwe" ],
            [ "state" => "imo", "state_id" => 17, "lg_name" => "Orlu" ],
            [ "state" => "imo", "state_id" => 17, "lg_name" => "Orsu" ],
            [ "state" => "imo", "state_id" => 17, "lg_name" => "Oru East" ],
            [ "state" => "imo", "state_id" => 17, "lg_name" => "Oru West" ],
            [ "state" => "imo", "state_id" => 17, "lg_name" => "Owerri Municipal" ],
            [ "state" => "imo", "state_id" => 17, "lg_name" => "Owerri North" ],
            [ "state" => "imo", "state_id" => 17, "lg_name" => "Owerri West" ],
            [ "state" => "imo", "state_id" => 17, "lg_name" => "Unuimo" ],
            [ "state" => "jigawa", "state_id" => 18, "lg_name" => "Auyo" ],
            [ "state" => "jigawa", "state_id" => 18, "lg_name" => "Babura" ],
            [ "state" => "jigawa", "state_id" => 18, "lg_name" => "Biriniwa" ],
            [ "state" => "jigawa", "state_id" => 18, "lg_name" => "Birnin Kudu" ],
            [ "state" => "jigawa", "state_id" => 18, "lg_name" => "Buji" ],
            [ "state" => "jigawa", "state_id" => 18, "lg_name" => "Dutse" ],
            [ "state" => "jigawa", "state_id" => 18, "lg_name" => "Gagarawa" ],
            [ "state" => "jigawa", "state_id" => 18, "lg_name" => "Garki" ],
            [ "state" => "jigawa", "state_id" => 18, "lg_name" => "Gumel" ],
            [ "state" => "jigawa", "state_id" => 18, "lg_name" => "Guri" ],
            [ "state" => "jigawa", "state_id" => 18, "lg_name" => "Gwaram" ],
            [ "state" => "jigawa", "state_id" => 18, "lg_name" => "Gwiwa" ],
            [ "state" => "jigawa", "state_id" => 18, "lg_name" => "Hadejia" ],
            [ "state" => "jigawa", "state_id" => 18, "lg_name" => "Jahun" ],
            [ "state" => "jigawa", "state_id" => 18, "lg_name" => "Kafin Hausa" ],
            [ "state" => "jigawa", "state_id" => 18, "lg_name" => "Kazaure" ],
            [ "state" => "jigawa", "state_id" => 18, "lg_name" => "Kiri Kasama" ],
            [ "state" => "jigawa", "state_id" => 18, "lg_name" => "Kiyawa" ],
            [ "state" => "jigawa", "state_id" => 18, "lg_name" => "Kaugama" ],
            [ "state" => "jigawa", "state_id" => 18, "lg_name" => "Maigatari" ],
            [ "state" => "jigawa", "state_id" => 18, "lg_name" => "Malam Madori" ],
            [ "state" => "jigawa", "state_id" => 18, "lg_name" => "Miga" ],
            [ "state" => "jigawa", "state_id" => 18, "lg_name" => "Ringim" ],
            [ "state" => "jigawa", "state_id" => 18, "lg_name" => "Roni" ],
            [ "state" => "jigawa", "state_id" => 18, "lg_name" => "Sule Tankarkar" ],
            [ "state" => "jigawa", "state_id" => 18, "lg_name" => "Taura" ],
            [ "state" => "jigawa", "state_id" => 18, "lg_name" => "Yankwashi" ],
            [ "state" => "kaduna", "state_id" => 19, "lg_name" => "Birnin Gwari" ],
            [ "state" => "kaduna", "state_id" => 19, "lg_name" => "Chikun" ],
            [ "state" => "kaduna", "state_id" => 19, "lg_name" => "Giwa" ],
            [ "state" => "kaduna", "state_id" => 19, "lg_name" => "Igabi" ],
            [ "state" => "kaduna", "state_id" => 19, "lg_name" => "Ikara" ],
            [ "state" => "kaduna", "state_id" => 19, "lg_name" => "Jaba" ],
            [ "state" => "kaduna", "state_id" => 19, "lg_name" => "Jema'a" ],
            [ "state" => "kaduna", "state_id" => 19, "lg_name" => "Kachia" ],
            [ "state" => "kaduna", "state_id" => 19, "lg_name" => "Kaduna North" ],
            [ "state" => "kaduna", "state_id" => 19, "lg_name" => "Kaduna South" ],
            [ "state" => "kaduna", "state_id" => 19, "lg_name" => "Kagarko" ],
            [ "state" => "kaduna", "state_id" => 19, "lg_name" => "Kajuru" ],
            [ "state" => "kaduna", "state_id" => 19, "lg_name" => "Kaura" ],
            [ "state" => "kaduna", "state_id" => 19, "lg_name" => "Kauru" ],
            [ "state" => "kaduna", "state_id" => 19, "lg_name" => "Kubau" ],
            [ "state" => "kaduna", "state_id" => 19, "lg_name" => "Kudan" ],
            [ "state" => "kaduna", "state_id" => 19, "lg_name" => "Lere" ],
            [ "state" => "kaduna", "state_id" => 19, "lg_name" => "Makarfi" ],
            [ "state" => "kaduna", "state_id" => 19, "lg_name" => "Sabon Gari" ],
            [ "state" => "kaduna", "state_id" => 19, "lg_name" => "Sanga" ],
            [ "state" => "kaduna", "state_id" => 19, "lg_name" => "Soba" ],
            [ "state" => "kaduna", "state_id" => 19, "lg_name" => "Zangon Kataf" ],
            [ "state" => "kaduna", "state_id" => 19, "lg_name" => "Zaria" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Ajingi" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Albasu" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Bagwai" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Bebeji" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Bichi" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Bunkure" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Dala" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Dambatta" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Dawakin Kudu" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Dawakin Tofa" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Doguwa" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Fagge" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Gabasawa" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Garko" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Garun Mallam" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Gaya" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Gezawa" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Gwale" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Gwarzo" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Kabo" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Kano Municipal" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Karaye" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Kibiya" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Kiru" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Kumbotso" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Kunchi" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Kura" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Madobi" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Makoda" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Minjibir" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Nasarawa" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Rano" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Rimin Gado" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Rogo" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Shanono" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Sumaila" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Takai" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Tarauni" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Tofa" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Tsanyawa" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Tudun Wada" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Ungogo" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Warawa" ],
            [ "state" => "kano", "state_id" => 20, "lg_name" => "Wudil" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Bakori" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Batagarawa" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Batsari" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Baure" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Bindawa" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Charanchi" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Dandume" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Danja" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Dan Musa" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Daura" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Dutsi" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Dutsin Ma" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Faskari" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Funtua" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Ingawa" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Jibia" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Kafur" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Kaita" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Kankara" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Kankia" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Katsina" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Kurfi" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Kusada" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Mai'Adua" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Malumfashi" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Mani" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Mashi" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Matazu" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Musawa" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Rimi" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Sabuwa" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Safana" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Sandamu" ],
            [ "state" => "katsina", "state_id" => 21, "lg_name" => "Zango" ],
            [ "state" => "kebbi", "state_id" => 22, "lg_name" => "Aleiro" ],
            [ "state" => "kebbi", "state_id" => 22, "lg_name" => "Arewa Dandi" ],
            [ "state" => "kebbi", "state_id" => 22, "lg_name" => "Argungu" ],
            [ "state" => "kebbi", "state_id" => 22, "lg_name" => "Augie" ],
            [ "state" => "kebbi", "state_id" => 22, "lg_name" => "Bagudo" ],
            [ "state" => "kebbi", "state_id" => 22, "lg_name" => "Birnin Kebbi" ],
            [ "state" => "kebbi", "state_id" => 22, "lg_name" => "Bunza" ],
            [ "state" => "kebbi", "state_id" => 22, "lg_name" => "Dandi" ],
            [ "state" => "kebbi", "state_id" => 22, "lg_name" => "Fakai" ],
            [ "state" => "kebbi", "state_id" => 22, "lg_name" => "Gwandu" ],
            [ "state" => "kebbi", "state_id" => 22, "lg_name" => "Jega" ],
            [ "state" => "kebbi", "state_id" => 22, "lg_name" => "Kalgo" ],
            [ "state" => "kebbi", "state_id" => 22, "lg_name" => "Koko Besse" ],
            [ "state" => "kebbi", "state_id" => 22, "lg_name" => "Maiyama" ],
            [ "state" => "kebbi", "state_id" => 22, "lg_name" => "Ngaski" ],
            [ "state" => "kebbi", "state_id" => 22, "lg_name" => "Sakaba" ],
            [ "state" => "kebbi", "state_id" => 22, "lg_name" => "Shanga" ],
            [ "state" => "kebbi", "state_id" => 22, "lg_name" => "Suru" ],
            [ "state" => "kebbi", "state_id" => 22, "lg_name" => "Wasagu Danko" ],
            [ "state" => "kebbi", "state_id" => 22, "lg_name" => "Yauri" ],
            [ "state" => "kebbi", "state_id" => 22, "lg_name" => "Zuru" ],
            [ "state" => "kogi", "state_id" => 23, "lg_name" => "Adavi" ],
            [ "state" => "kogi", "state_id" => 23, "lg_name" => "Ajaokuta" ],
            [ "state" => "kogi", "state_id" => 23, "lg_name" => "Ankpa" ],
            [ "state" => "kogi", "state_id" => 23, "lg_name" => "Bassa" ],
            [ "state" => "kogi", "state_id" => 23, "lg_name" => "Dekina" ],
            [ "state" => "kogi", "state_id" => 23, "lg_name" => "Ibaji" ],
            [ "state" => "kogi", "state_id" => 23, "lg_name" => "Idah" ],
            [ "state" => "kogi", "state_id" => 23, "lg_name" => "Igalamela Odolu" ],
            [ "state" => "kogi", "state_id" => 23, "lg_name" => "Ijumu" ],
            [ "state" => "kogi", "state_id" => 23, "lg_name" => "Kabba Bunu" ],
            [ "state" => "kogi", "state_id" => 23, "lg_name" => "Kogi" ],
            [ "state" => "kogi", "state_id" => 23, "lg_name" => "Lokoja" ],
            [ "state" => "kogi", "state_id" => 23, "lg_name" => "Mopa Muro" ],
            [ "state" => "kogi", "state_id" => 23, "lg_name" => "Ofu" ],
            [ "state" => "kogi", "state_id" => 23, "lg_name" => "Ogori Magongo" ],
            [ "state" => "kogi", "state_id" => 23, "lg_name" => "Okehi" ],
            [ "state" => "kogi", "state_id" => 23, "lg_name" => "Okene" ],
            [ "state" => "kogi", "state_id" => 23, "lg_name" => "Olamaboro" ],
            [ "state" => "kogi", "state_id" => 23, "lg_name" => "Omala" ],
            [ "state" => "kogi", "state_id" => 23, "lg_name" => "Yagba East" ],
            [ "state" => "kogi", "state_id" => 23, "lg_name" => "Yagba West" ],
            [ "state" => "kwara", "state_id" => 24, "lg_name" => "Asa" ],
            [ "state" => "kwara", "state_id" => 24, "lg_name" => "Baruten" ],
            [ "state" => "kwara", "state_id" => 24, "lg_name" => "Edu" ],
            [ "state" => "kwara", "state_id" => 24, "lg_name" => "Ekiti" ],
            [ "state" => "kwara", "state_id" => 24, "lg_name" => "Ifelodun" ],
            [ "state" => "kwara", "state_id" => 24, "lg_name" => "Ilorin East" ],
            [ "state" => "kwara", "state_id" => 24, "lg_name" => "Ilorin South" ],
            [ "state" => "kwara", "state_id" => 24, "lg_name" => "Ilorin West" ],
            [ "state" => "kwara", "state_id" => 24, "lg_name" => "Irepodun" ],
            [ "state" => "kwara", "state_id" => 24, "lg_name" => "Isin" ],
            [ "state" => "kwara", "state_id" => 24, "lg_name" => "Kaiama" ],
            [ "state" => "kwara", "state_id" => 24, "lg_name" => "Moro" ],
            [ "state" => "kwara", "state_id" => 24, "lg_name" => "Offa" ],
            [ "state" => "kwara", "state_id" => 24, "lg_name" => "Oke Ero" ],
            [ "state" => "kwara", "state_id" => 24, "lg_name" => "Oyun" ],
            [ "state" => "kwara", "state_id" => 24, "lg_name" => "Pategi" ],
            [ "state" => "lagos", "state_id" => 25, "lg_name" => "Agege" ],
            [ "state" => "lagos", "state_id" => 25, "lg_name" => "Ajeromi-Ifelodun" ],
            [ "state" => "lagos", "state_id" => 25, "lg_name" => "Alimosho" ],
            [ "state" => "lagos", "state_id" => 25, "lg_name" => "Amuwo-Odofin" ],
            [ "state" => "lagos", "state_id" => 25, "lg_name" => "Apapa" ],
            [ "state" => "lagos", "state_id" => 25, "lg_name" => "Badagry" ],
            [ "state" => "lagos", "state_id" => 25, "lg_name" => "Epe" ],
            [ "state" => "lagos", "state_id" => 25, "lg_name" => "Eti Osa" ],
            [ "state" => "lagos", "state_id" => 25, "lg_name" => "Ibeju-Lekki" ],
            [ "state" => "lagos", "state_id" => 25, "lg_name" => "Ifako-Ijaiye" ],
            [ "state" => "lagos", "state_id" => 25, "lg_name" => "Ikeja" ],
            [ "state" => "lagos", "state_id" => 25, "lg_name" => "Ikorodu" ],
            [ "state" => "lagos", "state_id" => 25, "lg_name" => "Kosofe" ],
            [ "state" => "lagos", "state_id" => 25, "lg_name" => "Lagos Island" ],
            [ "state" => "lagos", "state_id" => 25, "lg_name" => "Lagos Mainland" ],
            [ "state" => "lagos", "state_id" => 25, "lg_name" => "Mushin" ],
            [ "state" => "lagos", "state_id" => 25, "lg_name" => "Ojo" ],
            [ "state" => "lagos", "state_id" => 25, "lg_name" => "Oshodi-Isolo" ],
            [ "state" => "lagos", "state_id" => 25, "lg_name" => "Shomolu" ],
            [ "state" => "lagos", "state_id" => 25, "lg_name" => "Surulere" ],
            [ "state" => "nasarawa", "state_id" => 26, "lg_name" => "Akwanga" ],
            [ "state" => "nasarawa", "state_id" => 26, "lg_name" => "Awe" ],
            [ "state" => "nasarawa", "state_id" => 26, "lg_name" => "Doma" ],
            [ "state" => "nasarawa", "state_id" => 26, "lg_name" => "Karu" ],
            [ "state" => "nasarawa", "state_id" => 26, "lg_name" => "Keana" ],
            [ "state" => "nasarawa", "state_id" => 26, "lg_name" => "Keffi" ],
            [ "state" => "nasarawa", "state_id" => 26, "lg_name" => "Kokona" ],
            [ "state" => "nasarawa", "state_id" => 26, "lg_name" => "Lafia" ],
            [ "state" => "nasarawa", "state_id" => 26, "lg_name" => "Nasarawa" ],
            [ "state" => "nasarawa", "state_id" => 26, "lg_name" => "Nasarawa Egon" ],
            [ "state" => "nasarawa", "state_id" => 26, "lg_name" => "Obi" ],
            [ "state" => "nasarawa", "state_id" => 26, "lg_name" => "Toto" ],
            [ "state" => "nasarawa", "state_id" => 26, "lg_name" => "Wamba" ],
            [ "state" => "niger", "state_id" => 27, "lg_name" => "Agaie" ],
            [ "state" => "niger", "state_id" => 27, "lg_name" => "Agwara" ],
            [ "state" => "niger", "state_id" => 27, "lg_name" => "Bida" ],
            [ "state" => "niger", "state_id" => 27, "lg_name" => "Borgu" ],
            [ "state" => "niger", "state_id" => 27, "lg_name" => "Bosso" ],
            [ "state" => "niger", "state_id" => 27, "lg_name" => "Chanchaga" ],
            [ "state" => "niger", "state_id" => 27, "lg_name" => "Edati" ],
            [ "state" => "niger", "state_id" => 27, "lg_name" => "Gbako" ],
            [ "state" => "niger", "state_id" => 27, "lg_name" => "Gurara" ],
            [ "state" => "niger", "state_id" => 27, "lg_name" => "Katcha" ],
            [ "state" => "niger", "state_id" => 27, "lg_name" => "Kontagora" ],
            [ "state" => "niger", "state_id" => 27, "lg_name" => "Lapai" ],
            [ "state" => "niger", "state_id" => 27, "lg_name" => "Lavun" ],
            [ "state" => "niger", "state_id" => 27, "lg_name" => "Magama" ],
            [ "state" => "niger", "state_id" => 27, "lg_name" => "Mariga" ],
            [ "state" => "niger", "state_id" => 27, "lg_name" => "Mashegu" ],
            [ "state" => "niger", "state_id" => 27, "lg_name" => "Mokwa" ],
            [ "state" => "niger", "state_id" => 27, "lg_name" => "Moya" ],
            [ "state" => "niger", "state_id" => 27, "lg_name" => "Paikoro" ],
            [ "state" => "niger", "state_id" => 27, "lg_name" => "Rafi" ],
            [ "state" => "niger", "state_id" => 27, "lg_name" => "Rijau" ],
            [ "state" => "niger", "state_id" => 27, "lg_name" => "Shiroro" ],
            [ "state" => "niger", "state_id" => 27, "lg_name" => "Suleja" ],
            [ "state" => "niger", "state_id" => 27, "lg_name" => "Tafa" ],
            [ "state" => "niger", "state_id" => 27, "lg_name" => "Wushishi" ],
            [ "state" => "ogun", "state_id" => 28, "lg_name" => "Abeokuta North" ],
            [ "state" => "ogun", "state_id" => 28, "lg_name" => "Abeokuta South" ],
            [ "state" => "ogun", "state_id" => 28, "lg_name" => "Ado-Odo Ota" ],
            [ "state" => "ogun", "state_id" => 28, "lg_name" => "Yewa North" ],
            [ "state" => "ogun", "state_id" => 28, "lg_name" => "Yewa South" ],
            [ "state" => "ogun", "state_id" => 28, "lg_name" => "Ewekoro" ],
            [ "state" => "ogun", "state_id" => 28, "lg_name" => "Ifo" ],
            [ "state" => "ogun", "state_id" => 28, "lg_name" => "Ijebu East" ],
            [ "state" => "ogun", "state_id" => 28, "lg_name" => "Ijebu North" ],
            [ "state" => "ogun", "state_id" => 28, "lg_name" => "Ijebu North East" ],
            [ "state" => "ogun", "state_id" => 28, "lg_name" => "Ijebu Ode" ],
            [ "state" => "ogun", "state_id" => 28, "lg_name" => "Ikenne" ],
            [ "state" => "ogun", "state_id" => 28, "lg_name" => "Imeko Afon" ],
            [ "state" => "ogun", "state_id" => 28, "lg_name" => "Ipokia" ],
            [ "state" => "ogun", "state_id" => 28, "lg_name" => "Obafemi Owode" ],
            [ "state" => "ogun", "state_id" => 28, "lg_name" => "Odeda" ],
            [ "state" => "ogun", "state_id" => 28, "lg_name" => "Odogbolu" ],
            [ "state" => "ogun", "state_id" => 28, "lg_name" => "Ogun Waterside" ],
            [ "state" => "ogun", "state_id" => 28, "lg_name" => "Remo North" ],
            [ "state" => "ogun", "state_id" => 28, "lg_name" => "Shagamu" ],
            [ "state" => "ondo", "state_id" => 29, "lg_name" => "Akoko North-East" ],
            [ "state" => "ondo", "state_id" => 29, "lg_name" => "Akoko North-West" ],
            [ "state" => "ondo", "state_id" => 29, "lg_name" => "Akoko South-West" ],
            [ "state" => "ondo", "state_id" => 29, "lg_name" => "Akoko South-East" ],
            [ "state" => "ondo", "state_id" => 29, "lg_name" => "Akure North" ],
            [ "state" => "ondo", "state_id" => 29, "lg_name" => "Akure South" ],
            [ "state" => "ondo", "state_id" => 29, "lg_name" => "Ese Odo" ],
            [ "state" => "ondo", "state_id" => 29, "lg_name" => "Idanre" ],
            [ "state" => "ondo", "state_id" => 29, "lg_name" => "Ifedore" ],
            [ "state" => "ondo", "state_id" => 29, "lg_name" => "Ilaje" ],
            [ "state" => "ondo", "state_id" => 29, "lg_name" => "Ile Oluji Okeigbo" ],
            [ "state" => "ondo", "state_id" => 29, "lg_name" => "Irele" ],
            [ "state" => "ondo", "state_id" => 29, "lg_name" => "Odigbo" ],
            [ "state" => "ondo", "state_id" => 29, "lg_name" => "Okitipupa" ],
            [ "state" => "ondo", "state_id" => 29, "lg_name" => "Ondo East" ],
            [ "state" => "ondo", "state_id" => 29, "lg_name" => "Ondo West" ],
            [ "state" => "ondo", "state_id" => 29, "lg_name" => "Ose" ],
            [ "state" => "ondo", "state_id" => 29, "lg_name" => "Owo" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Osogbo" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Atakunmosa East" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Atakunmosa West" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Aiyedaade" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Aiyedire" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Boluwaduro" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Boripe" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Ede North" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Ede South" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Ife Central" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Ife East" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Ife North" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Ife South" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Egbedore" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Ejigbo" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Ifedayo" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Ifelodun" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Ila" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Ilesa East" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Ilesa West" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Irepodun" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Irewole" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Isokan" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Iwo" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Obokun" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Odo Otin" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Ola Oluwa" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Olorunda" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Oriade" ],
            [ "state" => "osun", "state_id" => 30, "lg_name" => "Orolu" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Afijio" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Akinyele" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Atiba" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Atisbo" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Egbeda" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Ibadan North" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Ibadan North-East" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Ibadan North-West" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Ibadan South-East" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Ibadan South-West" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Ibarapa Central" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Ibarapa East" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Ibarapa North" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Ido" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Irepo" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Iseyin" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Itesiwaju" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Iwajowa" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Kajola" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Lagelu" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Ogbomosho North" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Ogbomosho South" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Ogo Oluwa" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Olorunsogo" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Oluyole" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Ona Ara" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Orelope" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Ori Ire" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Oyo West" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Oyo East" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Saki East" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Saki West" ],
            [ "state" => "oyo", "state_id" => 31, "lg_name" => "Surulere" ],
            [ "state" => "plateau", "state_id" => 32, "lg_name" => "Bokkos" ],
            [ "state" => "plateau", "state_id" => 32, "lg_name" => "Barkin Ladi" ],
            [ "state" => "plateau", "state_id" => 32, "lg_name" => "Bassa" ],
            [ "state" => "plateau", "state_id" => 32, "lg_name" => "Jos East" ],
            [ "state" => "plateau", "state_id" => 32, "lg_name" => "Jos North" ],
            [ "state" => "plateau", "state_id" => 32, "lg_name" => "Jos South" ],
            [ "state" => "plateau", "state_id" => 32, "lg_name" => "Kanam" ],
            [ "state" => "plateau", "state_id" => 32, "lg_name" => "Kanke" ],
            [ "state" => "plateau", "state_id" => 32, "lg_name" => "Langtang South" ],
            [ "state" => "plateau", "state_id" => 32, "lg_name" => "Langtang North" ],
            [ "state" => "plateau", "state_id" => 32, "lg_name" => "Mangu" ],
            [ "state" => "plateau", "state_id" => 32, "lg_name" => "Mikang" ],
            [ "state" => "plateau", "state_id" => 32, "lg_name" => "Pankshin" ],
            [ "state" => "plateau", "state_id" => 32, "lg_name" => "Qua'an Pan" ],
            [ "state" => "plateau", "state_id" => 32, "lg_name" => "Riyom" ],
            [ "state" => "plateau", "state_id" => 32, "lg_name" => "Shendam" ],
            [ "state" => "plateau", "state_id" => 32, "lg_name" => "Wase" ],
            [ "state" => "rivers", "state_id" => 33, "lg_name" => "Abua Odual" ],
            [ "state" => "rivers", "state_id" => 33, "lg_name" => "Ahoada East" ],
            [ "state" => "rivers", "state_id" => 33, "lg_name" => "Ahoada West" ],
            [ "state" => "rivers", "state_id" => 33, "lg_name" => "Akuku-Toru" ],
            [ "state" => "rivers", "state_id" => 33, "lg_name" => "Andoni" ],
            [ "state" => "rivers", "state_id" => 33, "lg_name" => "Asari-Toru" ],
            [ "state" => "rivers", "state_id" => 33, "lg_name" => "Bonny" ],
            [ "state" => "rivers", "state_id" => 33, "lg_name" => "Degema" ],
            [ "state" => "rivers", "state_id" => 33, "lg_name" => "Eleme" ],
            [ "state" => "rivers", "state_id" => 33, "lg_name" => "Emuoha" ],
            [ "state" => "rivers", "state_id" => 33, "lg_name" => "Etche" ],
            [ "state" => "rivers", "state_id" => 33, "lg_name" => "Gokana" ],
            [ "state" => "rivers", "state_id" => 33, "lg_name" => "Ikwerre" ],
            [ "state" => "rivers", "state_id" => 33, "lg_name" => "Khana" ],
            [ "state" => "rivers", "state_id" => 33, "lg_name" => "Obio Akpor" ],
            [ "state" => "rivers", "state_id" => 33, "lg_name" => "Ogu Bolo" ],
            [ "state" => "rivers", "state_id" => 33, "lg_name" => "Ogba Egbema Ndoni" ],
            [ "state" => "rivers", "state_id" => 33, "lg_name" => "Okrika" ],
            [ "state" => "rivers", "state_id" => 33, "lg_name" => "Omuma" ],
            [ "state" => "rivers", "state_id" => 33, "lg_name" => "Opobo Nkoro" ],
            [ "state" => "rivers", "state_id" => 33, "lg_name" => "Oyigbo" ],
            [ "state" => "rivers", "state_id" => 33, "lg_name" => "Port Harcourt" ],
            [ "state" => "rivers", "state_id" => 33, "lg_name" => "Tai" ],
            [ "state" => "sokoto", "state_id" => 34, "lg_name" => "Binji" ],
            [ "state" => "sokoto", "state_id" => 34, "lg_name" => "Dange Shuni" ],
            [ "state" => "sokoto", "state_id" => 34, "lg_name" => "Bodinga" ],
            [ "state" => "sokoto", "state_id" => 34, "lg_name" => "Gada" ],
            [ "state" => "sokoto", "state_id" => 34, "lg_name" => "Goronyo" ],
            [ "state" => "sokoto", "state_id" => 34, "lg_name" => "Gudu" ],
            [ "state" => "sokoto", "state_id" => 34, "lg_name" => "Gwadabawa" ],
            [ "state" => "sokoto", "state_id" => 34, "lg_name" => "Illela" ],
            [ "state" => "sokoto", "state_id" => 34, "lg_name" => "Isa" ],
            [ "state" => "sokoto", "state_id" => 34, "lg_name" => "Kebbe" ],
            [ "state" => "sokoto", "state_id" => 34, "lg_name" => "Kware" ],
            [ "state" => "sokoto", "state_id" => 34, "lg_name" => "Rabah" ],
            [ "state" => "sokoto", "state_id" => 34, "lg_name" => "Sabon Birni" ],
            [ "state" => "sokoto", "state_id" => 34, "lg_name" => "Shagari" ],
            [ "state" => "sokoto", "state_id" => 34, "lg_name" => "Silame" ],
            [ "state" => "sokoto", "state_id" => 34, "lg_name" => "Sokoto North" ],
            [ "state" => "sokoto", "state_id" => 34, "lg_name" => "Sokoto South" ],
            [ "state" => "sokoto", "state_id" => 34, "lg_name" => "Tambuwal" ],
            [ "state" => "sokoto", "state_id" => 34, "lg_name" => "Tangaza" ],
            [ "state" => "sokoto", "state_id" => 34, "lg_name" => "Tureta" ],
            [ "state" => "sokoto", "state_id" => 34, "lg_name" => "Wamako" ],
            [ "state" => "sokoto", "state_id" => 34, "lg_name" => "Wurno" ],
            [ "state" => "sokoto", "state_id" => 34, "lg_name" => "Yabo" ],
            [ "state" => "taraba", "state_id" => 35, "lg_name" => "Ardo Kola" ],
            [ "state" => "taraba", "state_id" => 35, "lg_name" => "Bali" ],
            [ "state" => "taraba", "state_id" => 35, "lg_name" => "Donga" ],
            [ "state" => "taraba", "state_id" => 35, "lg_name" => "Gashaka" ],
            [ "state" => "taraba", "state_id" => 35, "lg_name" => "Gassol" ],
            [ "state" => "taraba", "state_id" => 35, "lg_name" => "Ibi" ],
            [ "state" => "taraba", "state_id" => 35, "lg_name" => "Jalingo" ],
            [ "state" => "taraba", "state_id" => 35, "lg_name" => "Karim Lamido" ],
            [ "state" => "taraba", "state_id" => 35, "lg_name" => "Kumi" ],
            [ "state" => "taraba", "state_id" => 35, "lg_name" => "Lau" ],
            [ "state" => "taraba", "state_id" => 35, "lg_name" => "Sardauna" ],
            [ "state" => "taraba", "state_id" => 35, "lg_name" => "Takum" ],
            [ "state" => "taraba", "state_id" => 35, "lg_name" => "Ussa" ],
            [ "state" => "taraba", "state_id" => 35, "lg_name" => "Wukari" ],
            [ "state" => "taraba", "state_id" => 35, "lg_name" => "Yorro" ],
            [ "state" => "taraba", "state_id" => 35, "lg_name" => "Zing" ],
            [ "state" => "yobe", "state_id" => 36, "lg_name" => "Bade" ],
            [ "state" => "yobe", "state_id" => 36, "lg_name" => "Bursari" ],
            [ "state" => "yobe", "state_id" => 36, "lg_name" => "Damaturu" ],
            [ "state" => "yobe", "state_id" => 36, "lg_name" => "Fika" ],
            [ "state" => "yobe", "state_id" => 36, "lg_name" => "Fune" ],
            [ "state" => "yobe", "state_id" => 36, "lg_name" => "Geidam" ],
            [ "state" => "yobe", "state_id" => 36, "lg_name" => "Gujba" ],
            [ "state" => "yobe", "state_id" => 36, "lg_name" => "Gulani" ],
            [ "state" => "yobe", "state_id" => 36, "lg_name" => "Jakusko" ],
            [ "state" => "yobe", "state_id" => 36, "lg_name" => "Karasuwa" ],
            [ "state" => "yobe", "state_id" => 36, "lg_name" => "Machina" ],
            [ "state" => "yobe", "state_id" => 36, "lg_name" => "Nangere" ],
            [ "state" => "yobe", "state_id" => 36, "lg_name" => "Nguru" ],
            [ "state" => "yobe", "state_id" => 36, "lg_name" => "Potiskum" ],
            [ "state" => "yobe", "state_id" => 36, "lg_name" => "Tarmuwa" ],
            [ "state" => "yobe", "state_id" => 36, "lg_name" => "Yunusari" ],
            [ "state" => "yobe", "state_id" => 36, "lg_name" => "Yusufari" ],
            [ "state" => "zamfara", "state_id" => 37, "lg_name" => "Anka" ],
            [ "state" => "zamfara", "state_id" => 37, "lg_name" => "Bakura" ],
            [ "state" => "zamfara", "state_id" => 37, "lg_name" => "Birnin Magaji Kiyaw" ],
            [ "state" => "zamfara", "state_id" => 37, "lg_name" => "Bukkuyum" ],
            [ "state" => "zamfara", "state_id" => 37, "lg_name" => "Bungudu" ],
            [ "state" => "zamfara", "state_id" => 37, "lg_name" => "Gummi" ],
            [ "state" => "zamfara", "state_id" => 37, "lg_name" => "Gusau" ],
            [ "state" => "zamfara", "state_id" => 37, "lg_name" => "Kaura Namoda" ],
            [ "state" => "zamfara", "state_id" => 37, "lg_name" => "Maradun" ],
            [ "state" => "zamfara", "state_id" => 37, "lg_name" => "Maru" ],
            [ "state" => "zamfara", "state_id" => 37, "lg_name" => "Shinkafi" ],
            [ "state" => "zamfara", "state_id" => 37, "lg_name" => "Talata Mafara" ],
            [ "state" => "zamfara", "state_id" => 37, "lg_name" => "Chafe" ],
            [ "state" => "zamfara", "state_id" => 37, "lg_name" => "Zurmi" ]
        ];

        foreach($lgas as $lga){
            Lga::create($lga);
        }
    }
}
